// Dog data with attributes (each attribute is 0-10 scale)
const dogs = [
    // Original 24 breeds
    {
        breed: "Labrador Retriever",
        size: 7,
        energy: 8,
        shedding: 7,
        vocal: 4,
        friendly: 9,
        independence: 3,
        grooming: 4,
        affection: 9,
        intelligence: 8,
        child_friendly: 9,
        pet_friendly: 8,
        health: 6,
        lifespan: 6,
        adaptability: 9,
        indoor_preference: 5,
        daytime_active: 8,
        cost: 5,
        hunting: 7
    },
    {
        breed: "German Shepherd",
        size: 8,
        energy: 7,
        shedding: 8,
        vocal: 5,
        friendly: 6,
        independence: 5,
        grooming: 6,
        affection: 7,
        intelligence: 9,
        child_friendly: 7,
        pet_friendly: 6,
        health: 5,
        lifespan: 6,
        adaptability: 8,
        indoor_preference: 4,
        daytime_active: 7,
        cost: 6,
        hunting: 6
    },
    {
        breed: "Poodle",
        size: 6,
        energy: 7,
        shedding: 1,
        vocal: 5,
        friendly: 8,
        independence: 4,
        grooming: 10,
        affection: 7,
        intelligence: 10,
        child_friendly: 8,
        pet_friendly: 7,
        health: 7,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 7,
        daytime_active: 7,
        cost: 7,
        hunting: 6
    },
    {
        breed: "Beagle",
        size: 4,
        energy: 8,
        shedding: 5,
        vocal: 8,
        friendly: 9,
        independence: 4,
        grooming: 3,
        affection: 8,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 9,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 5,
        hunting: 9
    },
    {
        breed: "Bulldog",
        size: 5,
        energy: 3,
        shedding: 5,
        vocal: 3,
        friendly: 7,
        independence: 5,
        grooming: 5,
        affection: 7,
        intelligence: 5,
        child_friendly: 8,
        pet_friendly: 7,
        health: 3,
        lifespan: 4,
        adaptability: 6,
        indoor_preference: 8,
        daytime_active: 5,
        cost: 7,
        hunting: 2
    },
    {
        breed: "Golden Retriever",
        size: 7,
        energy: 7,
        shedding: 8,
        vocal: 3,
        friendly: 10,
        independence: 2,
        grooming: 6,
        affection: 10,
        intelligence: 8,
        child_friendly: 10,
        pet_friendly: 9,
        health: 6,
        lifespan: 6,
        adaptability: 8,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 6,
        hunting: 6
    },
    {
        breed: "Siberian Husky",
        size: 6,
        energy: 9,
        shedding: 9,
        vocal: 8,
        friendly: 8,
        independence: 7,
        grooming: 7,
        affection: 6,
        intelligence: 7,
        child_friendly: 8,
        pet_friendly: 7,
        health: 7,
        lifespan: 7,
        adaptability: 6,
        indoor_preference: 3,
        daytime_active: 7,
        cost: 6,
        hunting: 7
    },
    {
        breed: "Chihuahua",
        size: 1,
        energy: 6,
        shedding: 4,
        vocal: 9,
        friendly: 5,
        independence: 6,
        grooming: 3,
        affection: 7,
        intelligence: 7,
        child_friendly: 4,
        pet_friendly: 5,
        health: 6,
        lifespan: 8,
        adaptability: 8,
        indoor_preference: 10,
        daytime_active: 6,
        cost: 5,
        hunting: 2
    },
    {
        breed: "Boxer",
        size: 7,
        energy: 8,
        shedding: 4,
        vocal: 3,
        friendly: 9,
        independence: 3,
        grooming: 2,
        affection: 9,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 7,
        health: 5,
        lifespan: 5,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 6,
        hunting: 5
    },
    {
        breed: "Shih Tzu",
        size: 2,
        energy: 4,
        shedding: 3,
        vocal: 5,
        friendly: 8,
        independence: 4,
        grooming: 9,
        affection: 8,
        intelligence: 6,
        child_friendly: 7,
        pet_friendly: 8,
        health: 6,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 6,
        hunting: 1
    },
    {
        breed: "Dachshund",
        size: 2,
        energy: 6,
        shedding: 5,
        vocal: 7,
        friendly: 6,
        independence: 5,
        grooming: 3,
        affection: 7,
        intelligence: 7,
        child_friendly: 6,
        pet_friendly: 5,
        health: 5,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 8,
        daytime_active: 7,
        cost: 5,
        hunting: 8
    },
    {
        breed: "Great Dane",
        size: 10,
        energy: 5,
        shedding: 6,
        vocal: 4,
        friendly: 8,
        independence: 4,
        grooming: 3,
        affection: 7,
        intelligence: 6,
        child_friendly: 8,
        pet_friendly: 7,
        health: 4,
        lifespan: 3,
        adaptability: 5,
        indoor_preference: 5,
        daytime_active: 6,
        cost: 8,
        hunting: 4
    },
    {
        breed: "Pomeranian",
        size: 1,
        energy: 7,
        shedding: 8,
        vocal: 8,
        friendly: 6,
        independence: 5,
        grooming: 8,
        affection: 7,
        intelligence: 7,
        child_friendly: 5,
        pet_friendly: 6,
        health: 6,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 7,
        cost: 6,
        hunting: 2
    },
    {
        breed: "Border Collie",
        size: 5,
        energy: 10,
        shedding: 7,
        vocal: 5,
        friendly: 7,
        independence: 5,
        grooming: 5,
        affection: 7,
        intelligence: 10,
        child_friendly: 7,
        pet_friendly: 6,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 4,
        daytime_active: 9,
        cost: 6,
        hunting: 7
    },
    {
        breed: "Australian Shepherd",
        size: 6,
        energy: 9,
        shedding: 7,
        vocal: 6,
        friendly: 7,
        independence: 4,
        grooming: 6,
        affection: 8,
        intelligence: 9,
        child_friendly: 8,
        pet_friendly: 7,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 5,
        daytime_active: 8,
        cost: 6,
        hunting: 6
    },
    {
        breed: "Doberman Pinscher",
        size: 8,
        energy: 7,
        shedding: 4,
        vocal: 5,
        friendly: 5,
        independence: 6,
        grooming: 2,
        affection: 6,
        intelligence: 9,
        child_friendly: 6,
        pet_friendly: 5,
        health: 6,
        lifespan: 6,
        adaptability: 7,
        indoor_preference: 5,
        daytime_active: 7,
        cost: 7,
        hunting: 5
    },
    {
        breed: "Rottweiler",
        size: 8,
        energy: 6,
        shedding: 6,
        vocal: 3,
        friendly: 5,
        independence: 5,
        grooming: 3,
        affection: 6,
        intelligence: 8,
        child_friendly: 7,
        pet_friendly: 5,
        health: 6,
        lifespan: 5,
        adaptability: 6,
        indoor_preference: 5,
        daytime_active: 7,
        cost: 7,
        hunting: 5
    },
    {
        breed: "Cavalier King Charles Spaniel",
        size: 3,
        energy: 5,
        shedding: 6,
        vocal: 4,
        friendly: 9,
        independence: 2,
        grooming: 7,
        affection: 10,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 9,
        health: 4,
        lifespan: 6,
        adaptability: 9,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 7,
        hunting: 3
    },
    {
        breed: "Pug",
        size: 3,
        energy: 4,
        shedding: 7,
        vocal: 5,
        friendly: 9,
        independence: 4,
        grooming: 4,
        affection: 9,
        intelligence: 6,
        child_friendly: 8,
        pet_friendly: 8,
        health: 3,
        lifespan: 5,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 6,
        hunting: 1
    },
    {
        breed: "Corgi",
        size: 3,
        energy: 8,
        shedding: 9,
        vocal: 7,
        friendly: 8,
        independence: 4,
        grooming: 6,
        affection: 8,
        intelligence: 8,
        child_friendly: 8,
        pet_friendly: 7,
        health: 5,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 7,
        daytime_active: 8,
        cost: 6,
        hunting: 6
    },
    {
        breed: "Jack Russell Terrier",
        size: 2,
        energy: 10,
        shedding: 5,
        vocal: 7,
        friendly: 7,
        independence: 5,
        grooming: 3,
        affection: 7,
        intelligence: 8,
        child_friendly: 7,
        pet_friendly: 6,
        health: 8,
        lifespan: 8,
        adaptability: 8,
        indoor_preference: 6,
        daytime_active: 9,
        cost: 5,
        hunting: 9
    },
    {
        breed: "Boston Terrier",
        size: 3,
        energy: 7,
        shedding: 3,
        vocal: 4,
        friendly: 9,
        independence: 4,
        grooming: 3,
        affection: 8,
        intelligence: 7,
        child_friendly: 8,
        pet_friendly: 7,
        health: 5,
        lifespan: 6,
        adaptability: 8,
        indoor_preference: 8,
        daytime_active: 7,
        cost: 6,
        hunting: 3
    },
    {
        breed: "Bernese Mountain Dog",
        size: 9,
        energy: 5,
        shedding: 8,
        vocal: 3,
        friendly: 9,
        independence: 3,
        grooming: 7,
        affection: 9,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 8,
        health: 3,
        lifespan: 3,
        adaptability: 6,
        indoor_preference: 5,
        daytime_active: 7,
        cost: 8,
        hunting: 3
    },
    {
        breed: "French Bulldog",
        size: 3,
        energy: 5,
        shedding: 4,
        vocal: 4,
        friendly: 8,
        independence: 4,
        grooming: 3,
        affection: 8,
        intelligence: 6,
        child_friendly: 7,
        pet_friendly: 7,
        health: 3,
        lifespan: 5,
        adaptability: 7,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 8,
        hunting: 1
    },
    
    // Adding additional breeds from the Dog API
    {
        breed: "Affenpinscher",
        size: 1,
        energy: 7,
        shedding: 2,
        vocal: 6,
        friendly: 6,
        independence: 5,
        grooming: 6,
        affection: 7,
        intelligence: 7,
        child_friendly: 5,
        pet_friendly: 5,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 9,
        daytime_active: 7,
        cost: 7,
        hunting: 3
    },
    {
        breed: "Afghan Hound",
        size: 7,
        energy: 6,
        shedding: 7,
        vocal: 3,
        friendly: 5,
        independence: 8,
        grooming: 10,
        affection: 5,
        intelligence: 6,
        child_friendly: 5,
        pet_friendly: 6,
        health: 6,
        lifespan: 7,
        adaptability: 5,
        indoor_preference: 6,
        daytime_active: 6,
        cost: 8,
        hunting: 7
    },
    {
        breed: "Airedale Terrier",
        size: 6,
        energy: 8,
        shedding: 3,
        vocal: 5,
        friendly: 6,
        independence: 7,
        grooming: 7,
        affection: 6,
        intelligence: 8,
        child_friendly: 7,
        pet_friendly: 5,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 5,
        daytime_active: 8,
        cost: 6,
        hunting: 8
    },
    {
        breed: "Akita",
        size: 8,
        energy: 6,
        shedding: 8,
        vocal: 2,
        friendly: 4,
        independence: 8,
        grooming: 7,
        affection: 5,
        intelligence: 7,
        child_friendly: 5,
        pet_friendly: 3,
        health: 5,
        lifespan: 6,
        adaptability: 6,
        indoor_preference: 5,
        daytime_active: 6,
        cost: 7,
        hunting: 6
    },
    {
        breed: "Alaskan Malamute",
        size: 8,
        energy: 7,
        shedding: 9,
        vocal: 5,
        friendly: 7,
        independence: 6,
        grooming: 7,
        affection: 6,
        intelligence: 7,
        child_friendly: 7,
        pet_friendly: 5,
        health: 6,
        lifespan: 6,
        adaptability: 6,
        indoor_preference: 3,
        daytime_active: 7,
        cost: 7,
        hunting: 5
    },
    {
        breed: "Basset Hound",
        size: 4,
        energy: 3,
        shedding: 5,
        vocal: 6,
        friendly: 8,
        independence: 6,
        grooming: 4,
        affection: 7,
        intelligence: 6,
        child_friendly: 8,
        pet_friendly: 8,
        health: 5,
        lifespan: 7,
        adaptability: 6,
        indoor_preference: 7,
        daytime_active: 5,
        cost: 5,
        hunting: 8
    },
    {
        breed: "Basenji",
        size: 3,
        energy: 7,
        shedding: 2,
        vocal: 2,
        friendly: 5,
        independence: 9,
        grooming: 2,
        affection: 5,
        intelligence: 7,
        child_friendly: 6,
        pet_friendly: 5,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 7,
        hunting: 8
    },
    {
        breed: "Bichon Frise",
        size: 2,
        energy: 6,
        shedding: 1,
        vocal: 5,
        friendly: 9,
        independence: 3,
        grooming: 9,
        affection: 9,
        intelligence: 7,
        child_friendly: 8,
        pet_friendly: 8,
        health: 7,
        lifespan: 8,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 7,
        cost: 7,
        hunting: 1
    },
    {
        breed: "Bloodhound",
        size: 8,
        energy: 5,
        shedding: 5,
        vocal: 6,
        friendly: 7,
        independence: 5,
        grooming: 4,
        affection: 7,
        intelligence: 6,
        child_friendly: 7,
        pet_friendly: 8,
        health: 5,
        lifespan: 6,
        adaptability: 5,
        indoor_preference: 5,
        daytime_active: 7,
        cost: 6,
        hunting: 10
    },
    {
        breed: "Bluetick Coonhound",
        size: 6,
        energy: 7,
        shedding: 4,
        vocal: 8,
        friendly: 7,
        independence: 6,
        grooming: 2,
        affection: 6,
        intelligence: 7,
        child_friendly: 7,
        pet_friendly: 7,
        health: 7,
        lifespan: 7,
        adaptability: 6,
        indoor_preference: 4,
        daytime_active: 8,
        cost: 5,
        hunting: 9
    },
    {
        breed: "Borzoi",
        size: 8,
        energy: 4,
        shedding: 5,
        vocal: 2,
        friendly: 5,
        independence: 8,
        grooming: 6,
        affection: 5,
        intelligence: 6,
        child_friendly: 6,
        pet_friendly: 6,
        health: 7,
        lifespan: 7,
        adaptability: 5,
        indoor_preference: 6,
        daytime_active: 6,
        cost: 7,
        hunting: 8
    },
    {
        breed: "Bull Terrier",
        size: 5,
        energy: 7,
        shedding: 5,
        vocal: 3,
        friendly: 7,
        independence: 5,
        grooming: 3,
        affection: 7,
        intelligence: 6,
        child_friendly: 6,
        pet_friendly: 5,
        health: 6,
        lifespan: 6,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 7,
        cost: 6,
        hunting: 5
    },
    {
        breed: "Cairn Terrier",
        size: 2,
        energy: 8,
        shedding: 3,
        vocal: 6,
        friendly: 6,
        independence: 6,
        grooming: 7,
        affection: 7,
        intelligence: 7,
        child_friendly: 7,
        pet_friendly: 6,
        health: 7,
        lifespan: 8,
        adaptability: 8,
        indoor_preference: 7,
        daytime_active: 8,
        cost: 6,
        hunting: 8
    },
    {
        breed: "Chow Chow",
        size: 6,
        energy: 3,
        shedding: 9,
        vocal: 2,
        friendly: 3,
        independence: 9,
        grooming: 8,
        affection: 4,
        intelligence: 5,
        child_friendly: 3,
        pet_friendly: 3,
        health: 5,
        lifespan: 6,
        adaptability: 5,
        indoor_preference: 7,
        daytime_active: 5,
        cost: 7,
        hunting: 4
    },
    {
        breed: "Cocker Spaniel",
        size: 4,
        energy: 6,
        shedding: 7,
        vocal: 5,
        friendly: 8,
        independence: 3,
        grooming: 8,
        affection: 8,
        intelligence: 7,
        child_friendly: 8,
        pet_friendly: 7,
        health: 5,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 7,
        daytime_active: 7,
        cost: 6,
        hunting: 7
    },
    {
        breed: "Collie",
        size: 6,
        energy: 6,
        shedding: 8,
        vocal: 6,
        friendly: 8,
        independence: 5,
        grooming: 7,
        affection: 7,
        intelligence: 8,
        child_friendly: 9,
        pet_friendly: 8,
        health: 6,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 7,
        cost: 6,
        hunting: 5
    },
    {
        breed: "Dalmatian",
        size: 6,
        energy: 8,
        shedding: 7,
        vocal: 4,
        friendly: 7,
        independence: 6,
        grooming: 3,
        affection: 7,
        intelligence: 7,
        child_friendly: 6,
        pet_friendly: 6,
        health: 5,
        lifespan: 6,
        adaptability: 6,
        indoor_preference: 5,
        daytime_active: 8,
        cost: 6,
        hunting: 5
    },
    {
        breed: "English Setter",
        size: 6,
        energy: 7,
        shedding: 5,
        vocal: 4,
        friendly: 8,
        independence: 4,
        grooming: 6,
        affection: 8,
        intelligence: 7,
        child_friendly: 8,
        pet_friendly: 8,
        health: 6,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 7,
        cost: 6,
        hunting: 8
    },
    {
        breed: "Fox Terrier",
        size: 3,
        energy: 9,
        shedding: 5,
        vocal: 7,
        friendly: 7,
        independence: 5,
        grooming: 6,
        affection: 7,
        intelligence: 8,
        child_friendly: 7,
        pet_friendly: 5,
        health: 7,
        lifespan: 8,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 6,
        hunting: 9
    },
    {
        breed: "Greyhound",
        size: 7,
        energy: 4,
        shedding: 3,
        vocal: 2,
        friendly: 7,
        independence: 6,
        grooming: 2,
        affection: 6,
        intelligence: 7,
        child_friendly: 7,
        pet_friendly: 7,
        health: 7,
        lifespan: 6,
        adaptability: 6,
        indoor_preference: 7,
        daytime_active: 5,
        cost: 6,
        hunting: 9
    },
    {
        breed: "Irish Setter",
        size: 7,
        energy: 8,
        shedding: 7,
        vocal: 5,
        friendly: 9,
        independence: 3,
        grooming: 7,
        affection: 8,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 8,
        health: 6,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 5,
        daytime_active: 8,
        cost: 6,
        hunting: 8
    },
    {
        breed: "Maltese",
        size: 1,
        energy: 5,
        shedding: 2,
        vocal: 6,
        friendly: 8,
        independence: 4,
        grooming: 9,
        affection: 9,
        intelligence: 7,
        child_friendly: 6,
        pet_friendly: 7,
        health: 6,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 7,
        hunting: 1
    },
    {
        breed: "Mastiff",
        size: 10,
        energy: 3,
        shedding: 5,
        vocal: 2,
        friendly: 6,
        independence: 5,
        grooming: 3,
        affection: 6,
        intelligence: 6,
        child_friendly: 6,
        pet_friendly: 5,
        health: 4,
        lifespan: 4,
        adaptability: 5,
        indoor_preference: 5,
        daytime_active: 5,
        cost: 8,
        hunting: 3
    },
    {
        breed: "Newfoundland",
        size: 9,
        energy: 4,
        shedding: 8,
        vocal: 3,
        friendly: 9,
        independence: 4,
        grooming: 8,
        affection: 9,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 8,
        health: 5,
        lifespan: 5,
        adaptability: 6,
        indoor_preference: 5,
        daytime_active: 5,
        cost: 8,
        hunting: 3
    },
    {
        breed: "Papillon",
        size: 1,
        energy: 7,
        shedding: 4,
        vocal: 7,
        friendly: 7,
        independence: 4,
        grooming: 7,
        affection: 8,
        intelligence: 9,
        child_friendly: 6,
        pet_friendly: 7,
        health: 7,
        lifespan: 8,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 7,
        cost: 6,
        hunting: 3
    },
    {
        breed: "Saint Bernard",
        size: 10,
        energy: 3,
        shedding: 8,
        vocal: 3,
        friendly: 9,
        independence: 3,
        grooming: 6,
        affection: 8,
        intelligence: 6,
        child_friendly: 8,
        pet_friendly: 7,
        health: 4,
        lifespan: 4,
        adaptability: 5,
        indoor_preference: 4,
        daytime_active: 5,
        cost: 9,
        hunting: 2
    },
    {
        breed: "Samoyed",
        size: 6,
        energy: 7,
        shedding: 9,
        vocal: 6,
        friendly: 9,
        independence: 5,
        grooming: 8,
        affection: 8,
        intelligence: 7,
        child_friendly: 8,
        pet_friendly: 7,
        health: 6,
        lifespan: 7,
        adaptability: 6,
        indoor_preference: 4,
        daytime_active: 7,
        cost: 7,
        hunting: 4
    },
    {
        breed: "Shetland Sheepdog",
        size: 3,
        energy: 7,
        shedding: 8,
        vocal: 7,
        friendly: 7,
        independence: 5,
        grooming: 8,
        affection: 7,
        intelligence: 9,
        child_friendly: 8,
        pet_friendly: 7,
        health: 6,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 6,
        hunting: 4
    },
    {
        breed: "Shiba Inu",
        size: 3,
        energy: 7,
        shedding: 7,
        vocal: 4,
        friendly: 5,
        independence: 9,
        grooming: 5,
        affection: 5,
        intelligence: 7,
        child_friendly: 6,
        pet_friendly: 5,
        health: 8,
        lifespan: 8,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 7,
        cost: 7,
        hunting: 7
    },
    {
        breed: "Vizsla",
        size: 6,
        energy: 9,
        shedding: 3,
        vocal: 3,
        friendly: 9,
        independence: 3,
        grooming: 2,
        affection: 9,
        intelligence: 8,
        child_friendly: 8,
        pet_friendly: 8,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 5,
        daytime_active: 8,
        cost: 7,
        hunting: 9
    },
    {
        breed: "Weimaraner",
        size: 7,
        energy: 9,
        shedding: 4,
        vocal: 5,
        friendly: 7,
        independence: 4,
        grooming: 2,
        affection: 8,
        intelligence: 8,
        child_friendly: 7,
        pet_friendly: 6,
        health: 7,
        lifespan: 6,
        adaptability: 6,
        indoor_preference: 4,
        daytime_active: 8,
        cost: 7,
        hunting: 9
    },
    {
        breed: "Yorkshire Terrier",
        size: 1,
        energy: 6,
        shedding: 2,
        vocal: 8,
        friendly: 6,
        independence: 5,
        grooming: 9,
        affection: 7,
        intelligence: 7,
        child_friendly: 5,
        pet_friendly: 5,
        health: 6,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 7,
        cost: 7,
        hunting: 3
    }
];

// Dog breed descriptions
const breedDescriptions = {
    // Original 24 breeds
    "Labrador Retriever": "Friendly, outgoing, and high-spirited companions with plenty of energy and affection for the whole family. Labs are versatile working dogs, happy to retrieve game, serve as therapy or service dogs, or just be loving family companions.",
    "German Shepherd": "Intelligent, loyal, and courageous dogs that excel as working dogs in roles like police and military service. They're protective of their families while also being affectionate and good with children when properly trained and socialized.",
    "Poodle": "Exceptionally smart and trainable dogs that come in three sizes: Standard, Miniature, and Toy. Despite their elegant appearance, Poodles were originally hunting dogs. They're active, proud, and very people-oriented.",
    "Beagle": "Merry, friendly hounds with great noses that were bred to hunt in packs. They're excellent with children and other dogs, though their tracking instincts can lead them to follow their noses regardless of commands.",
    "Bulldog": "Gentle, resolute companions with a distinctive pushed-in nose and wrinkled face. While they may look tough, they're generally docile and affectionate, making them good family pets despite some health challenges.",
    "Golden Retriever": "Friendly, reliable, and trustworthy dogs with hearts of gold. They excel at retrieving game for hunters, as service dogs, and as family companions. Their intelligence, patience, and gentle nature make them perfect for families.",
    "Siberian Husky": "Mischievous, athletic working dogs bred to pull sleds in cold climates. They have strong pack instincts and need plenty of exercise. Huskies are friendly but independent, with a strong prey drive and tendency to roam.",
    "Chihuahua": "Tiny dogs with huge personalities, known for being loyal and devoted to their people. They can be wary of strangers and are often protective despite their small size. They bond closely with one or two people in the family.",
    "Boxer": "Fun-loving, bright, and active dogs that make excellent family companions. They're patient and protective with children, playful well into adulthood, and maintain their puppy-like joy throughout their lives.",
    "Shih Tzu": "Affectionate, playful companions bred solely to be house pets and lap dogs. They're outgoing and friendly with strangers and other pets, and are known for their long, flowing coats that require regular grooming.",
    "Dachshund": "Bold, curious hounds with long bodies and short legs that were bred to hunt badgers and other burrowing animals. They're clever and courageous despite their small size, and come in three coat varieties.",
    "Great Dane": "Sweet-natured giants often called 'gentle giants.' Despite their imposing size, they're patient and friendly with family members, children, and other pets. They're moderately active and need space due to their size.",
    "Pomeranian": "Vivacious, intelligent little dogs with fox-like expressions and fluffy double coats. They're alert and make good watchdogs despite their tiny size. Poms are generally friendly but can be reserved with strangers.",
    "Border Collie": "Remarkably intelligent, energetic working dogs bred to herd sheep. They need extensive physical and mental exercise to prevent boredom and destructive behavior. They're incredibly focused and trainable when properly stimulated.",
    "Australian Shepherd": "Intelligent, work-oriented herding dogs with boundless energy and remarkable agility. They form strong bonds with their families but need jobs to do and plenty of exercise. 'Aussies' excel at dog sports and various working roles.",
    "Doberman Pinscher": "Loyal, fearless, and alert dogs originally bred as personal protectors. Modern Dobermans are affectionate and loyal family companions when properly trained and socialized, though still protective of their families.",
    "Rottweiler": "Confident, steady guardians with a calm, confident demeanor. They're loyal and protective of their families, making excellent guard dogs, but are also affectionate and playful with family members.",
    "Cavalier King Charles Spaniel": "Sweet, gentle companions that thrive on human contact. Their friendly nature makes them poor guard dogs but excellent therapy dogs and family pets. They're adaptable to various living situations and good with children.",
    "Pug": "Charming, mischievous companions with distinctive wrinkled faces and curled tails. They're playful and affectionate, content to be lap dogs but also enjoy short play sessions. Pugs can suffer from breathing problems due to their flat faces.",
    "Corgi": "Small but sturdy herding dogs with fox-like faces and bright expressions. Despite their short legs, they're agile and athletic. Corgis are intelligent, trainable, and make good watchdogs while being affectionate with family.",
    "Jack Russell Terrier": "Bold, energetic terriers originally bred for fox hunting. They're incredibly athletic and require vigorous daily exercise. Smart and determined, Jack Russells can be challenging for first-time dog owners due to their boundless energy.",
    "Boston Terrier": "Friendly, bright 'American Gentlemen' with tuxedo-like markings. They're playful, affectionate, and relatively quiet for a small breed. Boston Terriers are generally good with children and adapt well to apartment living.",
    "Bernese Mountain Dog": "Good-natured, calm working dogs from the Swiss Alps. They're gentle giants, devoted to their families and patient with children. Their thick coats helped them work in cold mountain conditions, but make them poorly suited to hot climates.",
    "French Bulldog": "Playful, smart companions with bat-like ears and distinctive flat faces. They're adaptable to city or country living and don't require much exercise. Frenchies are affectionate and make good apartment dogs despite some snoring and breathing issues.",
    
    // Additional breeds
    "Affenpinscher": "Small, sturdy 'monkey-like' terriers with a bold demeanor. Affenpinschers are playful, stubborn, and confident with a surprising toughness for their size. They're alert watchdogs and make amusing, loyal companions.",
    "Afghan Hound": "Elegant, dignified sighthounds with stunning flowing coats. Independent and somewhat aloof, Afghans were bred to hunt by sight and can be challenging to train. They're gentle with their families while maintaining a regal reserve.",
    "Airedale Terrier": "The 'King of Terriers' known for their versatility and independent spirit. Originally bred to hunt otters and rats, they're intelligent, strong-willed, and make excellent watchdogs while being affectionate with their families.",
    "Akita": "Powerful, dignified dogs originally from Japan. Known for their loyalty, Akitas are protective, courageous, and independent. They tend to bond closely with family but can be aloof with strangers and require firm, consistent training.",
    "Alaskan Malamute": "Powerful Arctic sled dogs with wolf-like appearances. Friendly and loyal, Malamutes were bred for endurance rather than speed. They're intelligent but independent, needing consistent training and plenty of exercise.",
    "Basset Hound": "Low-slung hounds with long ears and soulful expressions. Originally bred for hunting small game, Bassets are good-natured, patient companions with powerful noses. They can be stubborn and require patient training.",
    "Basenji": "Ancient African dogs known as the 'barkless dog.' Basenjis make unique yodeling sounds, are fastidiously clean like cats, and are independent with high prey drive. They're intelligent but can be challenging to train.",
    "Bichon Frise": "Cheerful, small white dogs with curly coats and playful personalities. Bichons were originally companion dogs and excel in this role today. They're good with children and other pets, and their non-shedding coats benefit allergy sufferers.",
    "Bloodhound": "Powerful scent hounds with incredible tracking abilities. Despite their formidable appearance, Bloodhounds are gentle, patient, and affectionate. Their strong tracking instinct can make them single-minded when following a scent.",
    "Bluetick Coonhound": "Athletic, determined hunting dogs with distinctive mottled coats. Originally bred to track raccoons, they have amazing stamina and powerful noses. They're friendly and laid-back at home but howl loudly when excited.",
    "Borzoi": "Elegant Russian sighthounds with quiet, cat-like personalities. Originally bred to hunt wolves, they're graceful, athletic, and surprisingly calm indoors. Independent thinkers, they require gentle training and space to run.",
    "Bull Terrier": "Distinctive egg-shaped heads and muscular bodies. Despite their tough appearance, Bull Terriers are playful, charming, and mischievous companions. They're stubborn but loving, requiring consistent training and plenty of exercise.",
    "Cairn Terrier": "Small, hardy terriers similar to the dog in 'The Wizard of Oz.' They're alert, spirited, and independent, having been bred to hunt vermin in the Scottish Highlands. Cairns are active and make loyal, entertaining companions.",
    "Chow Chow": "Distinguished by their lion-like manes and blue-black tongues. Chows are dignified, independent, and aloof with a cat-like personality. They're naturally clean but require regular brushing for their thick double coats.",
    "Cocker Spaniel": "Sweet-natured sporting dogs with beautiful coats and expressive eyes. They're gentle, eager to please, and good with children. Originally gun dogs, they maintain some hunting instincts while being primarily companion animals today.",
    "Collie": "Intelligent herders made famous by the 'Lassie' character. Collies are devoted to their families, especially children, and have a natural desire to please. They're sensitive, responsive to training, and make excellent family dogs.",
    "Dalmatian": "Distinctive spotted dogs originally bred as carriage dogs. They're athletic, intelligent, and have great endurance. Dalmatians need considerable exercise and can be somewhat stubborn, but they're loyal and make good watchdogs.",
    "English Setter": "Elegant sporting dogs with speckled coats and gentle dispositions. Originally bred to 'set' (point) upland game birds, they're friendly, good with children, and get along well with other pets. They need regular exercise and grooming.",
    "Fox Terrier": "Alert, active terriers that come in smooth and wire-coated varieties. Originally bred to flush foxes from their dens, they're fearless and energetic. Fox Terriers are playful companions that need regular activity and mental stimulation.",
    "Greyhound": "Known for incredible speed, Greyhounds are actually calm and quiet when indoors. Despite their racing background, they're gentle, sensitive companions who enjoy lounging on soft furniture. They have strong prey drive but bond closely with owners.",
    "Irish Setter": "Stunning red-coated sporting dogs with boundless energy and affectionate personalities. Originally gun dogs, they maintain their hunting instincts. Irish Setters are playful, good with children, but can be slow to mature and need patient training.",
    "Maltese": "Ancient toy breeds with silky white coats and gentle dispositions. Bred to be companions for thousands of years, they're affectionate and fearless despite their small size. Maltese are intelligent, trainable, and bond closely with their people.",
    "Mastiff": "Enormous, powerful guardian dogs with gentle dispositions. Among the largest breeds, Mastiffs are calm, dignified, and courageous. They're protective of their families while generally being good-natured and patient with considerate children.",
    "Newfoundland": "Massive, sweet-natured working dogs with water-resistant coats. Originally bred to help fishermen, they're natural lifeguards with webbed feet and amazing swimming ability. Newfies are gentle giants, devoted to their families, and good with children.",
    "Papillon": "Tiny dogs with distinctive butterfly-like ears. Despite their delicate appearance, Papillons are sturdy, athletic, and among the most intelligent toy breeds. They're playful, alert companions that excel in dog sports despite their small size.",
    "Saint Bernard": "Massive rescue dogs originally from the Swiss Alps. Known for their historical role in mountain rescues, they're patient, gentle giants with friendly dispositions. Saint Bernards are good with children but need space due to their size.",
    "Samoyed": "Beautiful white Arctic dogs with perpetual smiles. Originally bred for herding reindeer and pulling sleds, they're friendly, gentle companions. Samoyeds are intelligent but somewhat stubborn, and need regular exercise and grooming for their thick coats.",
    "Shetland Sheepdog": "Miniature Collie-like herding dogs with beautiful coats. Shelties are intelligent, eager to please, and excel at obedience and agility. They're sensitive, somewhat reserved with strangers, and very attached to their families.",
    "Shiba Inu": "Ancient Japanese breeds with fox-like appearances and independent personalities. Shibas are clean, fastidious, and alert, making good watchdogs. They're loyal to their families but can be aloof and strong-willed, requiring consistent training.",
    "Vizsla": "Sleek, athletic Hungarian pointing dogs with golden-rust coats. Vizslas are energetic, affectionate, and form strong bonds with their people. They need substantial exercise and aren't happy when left alone for long periods.",
    "Weimaraner": "Sleek, silver-gray sporting dogs known as 'the Gray Ghost.' Originally bred for hunting big game, they're athletic, intelligent, and have strong prey drive. Weimaraners bond intensely with their families and can suffer from separation anxiety.",
    "Yorkshire Terrier": "Tiny terriers with silky blue and tan coats. Despite their small size and glamorous appearance, Yorkies have terrier tenacity and make alert watchdogs. They're affectionate with their families while maintaining a feisty, confident attitude."
};

// Mapping between our breed names and The Dog API breed IDs/URLs
const dogApiBreedMap = {
    // Original 24 breeds
    "Labrador Retriever": "retriever/labrador",
    "German Shepherd": "germanshepherd",
    "Poodle": "poodle/standard",
    "Beagle": "beagle",
    "Bulldog": "bulldog/english",
    "Golden Retriever": "retriever/golden",
    "Siberian Husky": "husky",
    "Chihuahua": "chihuahua",
    "Boxer": "boxer",
    "Shih Tzu": "shihtzu",
    "Dachshund": "dachshund",
    "Great Dane": "dane/great",
    "Pomeranian": "pomeranian",
    "Border Collie": "collie/border",
    "Australian Shepherd": "australian/shepherd",
    "Doberman Pinscher": "doberman",
    "Rottweiler": "rottweiler",
    "Cavalier King Charles Spaniel": "spaniel/cavalier",
    "Pug": "pug",
    "Corgi": "corgi/cardigan",
    "Jack Russell Terrier": "terrier/russell",
    "Boston Terrier": "terrier/boston",
    "Bernese Mountain Dog": "mountain/bernese",
    "French Bulldog": "bulldog/french",
    
    // Additional breeds
    "Affenpinscher": "affenpinscher",
    "Afghan Hound": "hound/afghan",
    "Airedale Terrier": "airedale",
    "Akita": "akita",
    "Alaskan Malamute": "malamute",
    "Basset Hound": "hound/basset",
    "Basenji": "basenji",
    "Bichon Frise": "frise/bichon",
    "Bloodhound": "hound/blood",
    "Bluetick Coonhound": "bluetick",
    "Borzoi": "borzoi",
    "Bull Terrier": "bullterrier",
    "Cairn Terrier": "terrier/cairn",
    "Chow Chow": "chow",
    "Cocker Spaniel": "spaniel/cocker",
    "Collie": "collie",
    "Dalmatian": "dalmatian",
    "English Setter": "setter/english",
    "Fox Terrier": "terrier/fox",
    "Greyhound": "greyhound",
    "Irish Setter": "setter/irish",
    "Maltese": "maltese",
    "Mastiff": "mastiff",
    "Newfoundland": "newfoundland",
    "Papillon": "papillon",
    "Saint Bernard": "stbernard",
    "Samoyed": "samoyed",
    "Shetland Sheepdog": "sheepdog/shetland",
    "Shiba Inu": "shiba",
    "Vizsla": "vizsla",
    "Weimaraner": "weimaraner",
    "Yorkshire Terrier": "terrier/yorkshire"
};

// Questions to ask the user
const questions = [
    { id: "size", question: "How important is having a larger dog?", attribute: "size" },
    { id: "energy", question: "How important is having an energetic, playful dog?", attribute: "energy" },
    { id: "shedding", question: "How concerned are you about shedding? (10 = very concerned)", attribute: "shedding", invert: true },
    { id: "vocal", question: "How important is having a vocal, barking dog?", attribute: "vocal" },
    { id: "friendly", question: "How important is having a dog that's social and friendly with strangers?", attribute: "friendly" },
    { id: "independence", question: "How important is having a dog that's independent and can be left alone?", attribute: "independence" },
    { id: "grooming", question: "How concerned are you about grooming requirements? (10 = very concerned)", attribute: "grooming", invert: true },
    { id: "affection", question: "How important is having an affectionate, cuddly dog?", attribute: "affection" },
    { id: "intelligence", question: "How important is having an intelligent, trainable dog?", attribute: "intelligence" },
    { id: "child_friendly", question: "How important is having a dog that gets along well with children?", attribute: "child_friendly" },
    { id: "pet_friendly", question: "How important is having a dog that gets along with other pets?", attribute: "pet_friendly" },
    { id: "health", question: "How important is having a breed with fewer health issues?", attribute: "health" },
    { id: "lifespan", question: "How important is having a dog with a longer lifespan?", attribute: "lifespan" },
    { id: "adaptability", question: "How important is having a dog that adapts well to changes?", attribute: "adaptability" },
    { id: "indoor_preference", question: "How important is having a dog that's comfortable staying indoors?", attribute: "indoor_preference" },
    { id: "daytime_active", question: "How important is having a dog that's active during the day rather than night?", attribute: "daytime_active" },
    { id: "cost", question: "How concerned are you about the cost of ownership? (10 = very concerned)", attribute: "cost", invert: true },
    { id: "hunting", question: "How important is having a dog with strong hunting instincts?", attribute: "hunting" }
];