// Dog data with attributes (each attribute is 0-10 scale)
const dogs = [
    {
        breed: "Labrador Retriever",
        size: 7,
        energy: 8,
        shedding: 7,
        vocal: 4,
        friendly: 9,
        independence: 3,
        grooming: 4,
        affection: 9,
        intelligence: 8,
        child_friendly: 9,
        pet_friendly: 8,
        health: 6,
        lifespan: 6,
        adaptability: 9,
        indoor_preference: 5,
        daytime_active: 8,
        cost: 5,
        hunting: 7
    },
    {
        breed: "German Shepherd",
        size: 8,
        energy: 7,
        shedding: 8,
        vocal: 5,
        friendly: 6,
        independence: 5,
        grooming: 6,
        affection: 7,
        intelligence: 9,
        child_friendly: 7,
        pet_friendly: 6,
        health: 5,
        lifespan: 6,
        adaptability: 8,
        indoor_preference: 4,
        daytime_active: 7,
        cost: 6,
        hunting: 6
    },
    {
        breed: "Poodle",
        size: 6,
        energy: 7,
        shedding: 1,
        vocal: 5,
        friendly: 8,
        independence: 4,
        grooming: 10,
        affection: 7,
        intelligence: 10,
        child_friendly: 8,
        pet_friendly: 7,
        health: 7,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 7,
        daytime_active: 7,
        cost: 7,
        hunting: 6
    },
    {
        breed: "Beagle",
        size: 4,
        energy: 8,
        shedding: 5,
        vocal: 8,
        friendly: 9,
        independence: 4,
        grooming: 3,
        affection: 8,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 9,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 5,
        hunting: 9
    },
    {
        breed: "Bulldog",
        size: 5,
        energy: 3,
        shedding: 5,
        vocal: 3,
        friendly: 7,
        independence: 5,
        grooming: 5,
        affection: 7,
        intelligence: 5,
        child_friendly: 8,
        pet_friendly: 7,
        health: 3,
        lifespan: 4,
        adaptability: 6,
        indoor_preference: 8,
        daytime_active: 5,
        cost: 7,
        hunting: 2
    },
    {
        breed: "Golden Retriever",
        size: 7,
        energy: 7,
        shedding: 8,
        vocal: 3,
        friendly: 10,
        independence: 2,
        grooming: 6,
        affection: 10,
        intelligence: 8,
        child_friendly: 10,
        pet_friendly: 9,
        health: 6,
        lifespan: 6,
        adaptability: 8,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 6,
        hunting: 6
    },
    {
        breed: "Siberian Husky",
        size: 6,
        energy: 9,
        shedding: 9,
        vocal: 8,
        friendly: 8,
        independence: 7,
        grooming: 7,
        affection: 6,
        intelligence: 7,
        child_friendly: 8,
        pet_friendly: 7,
        health: 7,
        lifespan: 7,
        adaptability: 6,
        indoor_preference: 3,
        daytime_active: 7,
        cost: 6,
        hunting: 7
    },
    {
        breed: "Chihuahua",
        size: 1,
        energy: 6,
        shedding: 4,
        vocal: 9,
        friendly: 5,
        independence: 6,
        grooming: 3,
        affection: 7,
        intelligence: 7,
        child_friendly: 4,
        pet_friendly: 5,
        health: 6,
        lifespan: 8,
        adaptability: 8,
        indoor_preference: 10,
        daytime_active: 6,
        cost: 5,
        hunting: 2
    },
    {
        breed: "Boxer",
        size: 7,
        energy: 8,
        shedding: 4,
        vocal: 3,
        friendly: 9,
        independence: 3,
        grooming: 2,
        affection: 9,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 7,
        health: 5,
        lifespan: 5,
        adaptability: 7,
        indoor_preference: 6,
        daytime_active: 8,
        cost: 6,
        hunting: 5
    },
    {
        breed: "Shih Tzu",
        size: 2,
        energy: 4,
        shedding: 3,
        vocal: 5,
        friendly: 8,
        independence: 4,
        grooming: 9,
        affection: 8,
        intelligence: 6,
        child_friendly: 7,
        pet_friendly: 8,
        health: 6,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 6,
        hunting: 1
    },
    {
        breed: "Dachshund",
        size: 2,
        energy: 6,
        shedding: 5,
        vocal: 7,
        friendly: 6,
        independence: 5,
        grooming: 3,
        affection: 7,
        intelligence: 7,
        child_friendly: 6,
        pet_friendly: 5,
        health: 5,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 8,
        daytime_active: 7,
        cost: 5,
        hunting: 8
    },
    {
        breed: "Great Dane",
        size: 10,
        energy: 5,
        shedding: 6,
        vocal: 4,
        friendly: 8,
        independence: 4,
        grooming: 3,
        affection: 7,
        intelligence: 6,
        child_friendly: 8,
        pet_friendly: 7,
        health: 4,
        lifespan: 3,
        adaptability: 5,
        indoor_preference: 5,
        daytime_active: 6,
        cost: 8,
        hunting: 4
    },
    {
        breed: "Pomeranian",
        size: 1,
        energy: 7,
        shedding: 8,
        vocal: 8,
        friendly: 6,
        independence: 5,
        grooming: 8,
        affection: 7,
        intelligence: 7,
        child_friendly: 5,
        pet_friendly: 6,
        health: 6,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 7,
        cost: 6,
        hunting: 2
    },
    {
        breed: "Border Collie",
        size: 5,
        energy: 10,
        shedding: 7,
        vocal: 5,
        friendly: 7,
        independence: 5,
        grooming: 5,
        affection: 7,
        intelligence: 10,
        child_friendly: 7,
        pet_friendly: 6,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 4,
        daytime_active: 9,
        cost: 6,
        hunting: 7
    },
    {
        breed: "Australian Shepherd",
        size: 6,
        energy: 9,
        shedding: 7,
        vocal: 6,
        friendly: 7,
        independence: 4,
        grooming: 6,
        affection: 8,
        intelligence: 9,
        child_friendly: 8,
        pet_friendly: 7,
        health: 7,
        lifespan: 7,
        adaptability: 7,
        indoor_preference: 5,
        daytime_active: 8,
        cost: 6,
        hunting: 6
    },
    {
        breed: "Doberman Pinscher",
        size: 8,
        energy: 7,
        shedding: 4,
        vocal: 5,
        friendly: 5,
        independence: 6,
        grooming: 2,
        affection: 6,
        intelligence: 9,
        child_friendly: 6,
        pet_friendly: 5,
        health: 6,
        lifespan: 6,
        adaptability: 7,
        indoor_preference: 5,
        daytime_active: 7,
        cost: 7,
        hunting: 5
    },
    {
        breed: "Rottweiler",
        size: 8,
        energy: 6,
        shedding: 6,
        vocal: 3,
        friendly: 5,
        independence: 5,
        grooming: 3,
        affection: 6,
        intelligence: 8,
        child_friendly: 7,
        pet_friendly: 5,
        health: 6,
        lifespan: 5,
        adaptability: 6,
        indoor_preference: 5,
        daytime_active: 7,
        cost: 7,
        hunting: 5
    },
    {
        breed: "Cavalier King Charles Spaniel",
        size: 3,
        energy: 5,
        shedding: 6,
        vocal: 4,
        friendly: 9,
        independence: 2,
        grooming: 7,
        affection: 10,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 9,
        health: 4,
        lifespan: 6,
        adaptability: 9,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 7,
        hunting: 3
    },
    {
        breed: "Pug",
        size: 3,
        energy: 4,
        shedding: 7,
        vocal: 5,
        friendly: 9,
        independence: 4,
        grooming: 4,
        affection: 9,
        intelligence: 6,
        child_friendly: 8,
        pet_friendly: 8,
        health: 3,
        lifespan: 5,
        adaptability: 8,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 6,
        hunting: 1
    },
    {
        breed: "Corgi",
        size: 3,
        energy: 8,
        shedding: 9,
        vocal: 7,
        friendly: 8,
        independence: 4,
        grooming: 6,
        affection: 8,
        intelligence: 8,
        child_friendly: 8,
        pet_friendly: 7,
        health: 5,
        lifespan: 7,
        adaptability: 8,
        indoor_preference: 7,
        daytime_active: 8,
        cost: 6,
        hunting: 6
    },
    {
        breed: "Jack Russell Terrier",
        size: 2,
        energy: 10,
        shedding: 5,
        vocal: 7,
        friendly: 7,
        independence: 5,
        grooming: 3,
        affection: 7,
        intelligence: 8,
        child_friendly: 7,
        pet_friendly: 6,
        health: 8,
        lifespan: 8,
        adaptability: 8,
        indoor_preference: 6,
        daytime_active: 9,
        cost: 5,
        hunting: 9
    },
    {
        breed: "Boston Terrier",
        size: 3,
        energy: 7,
        shedding: 3,
        vocal: 4,
        friendly: 9,
        independence: 4,
        grooming: 3,
        affection: 8,
        intelligence: 7,
        child_friendly: 8,
        pet_friendly: 7,
        health: 5,
        lifespan: 6,
        adaptability: 8,
        indoor_preference: 8,
        daytime_active: 7,
        cost: 6,
        hunting: 3
    },
    {
        breed: "Bernese Mountain Dog",
        size: 9,
        energy: 5,
        shedding: 8,
        vocal: 3,
        friendly: 9,
        independence: 3,
        grooming: 7,
        affection: 9,
        intelligence: 7,
        child_friendly: 9,
        pet_friendly: 8,
        health: 3,
        lifespan: 3,
        adaptability: 6,
        indoor_preference: 5,
        daytime_active: 7,
        cost: 8,
        hunting: 3
    },
    {
        breed: "French Bulldog",
        size: 3,
        energy: 5,
        shedding: 4,
        vocal: 4,
        friendly: 8,
        independence: 4,
        grooming: 3,
        affection: 8,
        intelligence: 6,
        child_friendly: 7,
        pet_friendly: 7,
        health: 3,
        lifespan: 5,
        adaptability: 7,
        indoor_preference: 9,
        daytime_active: 6,
        cost: 8,
        hunting: 1
    }
];

// Dog breed descriptions
const breedDescriptions = {
    "Labrador Retriever": "Friendly, outgoing, and high-spirited companions with plenty of energy and affection for the whole family. Labs are versatile working dogs, happy to retrieve game, serve as therapy or service dogs, or just be loving family companions.",
    "German Shepherd": "Intelligent, loyal, and courageous dogs that excel as working dogs in roles like police and military service. They're protective of their families while also being affectionate and good with children when properly trained and socialized.",
    "Poodle": "Exceptionally smart and trainable dogs that come in three sizes: Standard, Miniature, and Toy. Despite their elegant appearance, Poodles were originally hunting dogs. They're active, proud, and very people-oriented.",
    "Beagle": "Merry, friendly hounds with great noses that were bred to hunt in packs. They're excellent with children and other dogs, though their tracking instincts can lead them to follow their noses regardless of commands.",
    "Bulldog": "Gentle, resolute companions with a distinctive pushed-in nose and wrinkled face. While they may look tough, they're generally docile and affectionate, making them good family pets despite some health challenges.",
    "Golden Retriever": "Friendly, reliable, and trustworthy dogs with hearts of gold. They excel at retrieving game for hunters, as service dogs, and as family companions. Their intelligence, patience, and gentle nature make them perfect for families.",
    "Siberian Husky": "Mischievous, athletic working dogs bred to pull sleds in cold climates. They have strong pack instincts and need plenty of exercise. Huskies are friendly but independent, with a strong prey drive and tendency to roam.",
    "Chihuahua": "Tiny dogs with huge personalities, known for being loyal and devoted to their people. They can be wary of strangers and are often protective despite their small size. They bond closely with one or two people in the family.",
    "Boxer": "Fun-loving, bright, and active dogs that make excellent family companions. They're patient and protective with children, playful well into adulthood, and maintain their puppy-like joy throughout their lives.",
    "Shih Tzu": "Affectionate, playful companions bred solely to be house pets and lap dogs. They're outgoing and friendly with strangers and other pets, and are known for their long, flowing coats that require regular grooming.",
    "Dachshund": "Bold, curious hounds with long bodies and short legs that were bred to hunt badgers and other burrowing animals. They're clever and courageous despite their small size, and come in three coat varieties.",
    "Great Dane": "Sweet-natured giants often called 'gentle giants.' Despite their imposing size, they're patient and friendly with family members, children, and other pets. They're moderately active and need space due to their size.",
    "Pomeranian": "Vivacious, intelligent little dogs with fox-like expressions and fluffy double coats. They're alert and make good watchdogs despite their tiny size. Poms are generally friendly but can be reserved with strangers.",
    "Border Collie": "Remarkably intelligent, energetic working dogs bred to herd sheep. They need extensive physical and mental exercise to prevent boredom and destructive behavior. They're incredibly focused and trainable when properly stimulated.",
    "Australian Shepherd": "Intelligent, work-oriented herding dogs with boundless energy and remarkable agility. They form strong bonds with their families but need jobs to do and plenty of exercise. 'Aussies' excel at dog sports and various working roles.",
    "Doberman Pinscher": "Loyal, fearless, and alert dogs originally bred as personal protectors. Modern Dobermans are affectionate and loyal family companions when properly trained and socialized, though still protective of their families.",
    "Rottweiler": "Confident, steady guardians with a calm, confident demeanor. They're loyal and protective of their families, making excellent guard dogs, but are also affectionate and playful with family members.",
    "Cavalier King Charles Spaniel": "Sweet, gentle companions that thrive on human contact. Their friendly nature makes them poor guard dogs but excellent therapy dogs and family pets. They're adaptable to various living situations and good with children.",
    "Pug": "Charming, mischievous companions with distinctive wrinkled faces and curled tails. They're playful and affectionate, content to be lap dogs but also enjoy short play sessions. Pugs can suffer from breathing problems due to their flat faces.",
    "Corgi": "Small but sturdy herding dogs with fox-like faces and bright expressions. Despite their short legs, they're agile and athletic. Corgis are intelligent, trainable, and make good watchdogs while being affectionate with family.",
    "Jack Russell Terrier": "Bold, energetic terriers originally bred for fox hunting. They're incredibly athletic and require vigorous daily exercise. Smart and determined, Jack Russells can be challenging for first-time dog owners due to their boundless energy.",
    "Boston Terrier": "Friendly, bright 'American Gentlemen' with tuxedo-like markings. They're playful, affectionate, and relatively quiet for a small breed. Boston Terriers are generally good with children and adapt well to apartment living.",
    "Bernese Mountain Dog": "Good-natured, calm working dogs from the Swiss Alps. They're gentle giants, devoted to their families and patient with children. Their thick coats helped them work in cold mountain conditions, but make them poorly suited to hot climates.",
    "French Bulldog": "Playful, smart companions with bat-like ears and distinctive flat faces. They're adaptable to city or country living and don't require much exercise. Frenchies are affectionate and make good apartment dogs despite some snoring and breathing issues."
};

// Mapping between our breed names and The Dog API breed IDs/URLs
const dogApiBreedMap = {
    "Labrador Retriever": "retriever/labrador",
    "German Shepherd": "germanshepherd",
    "Poodle": "poodle/standard",
    "Beagle": "beagle",
    "Bulldog": "bulldog/english",
    "Golden Retriever": "retriever/golden",
    "Siberian Husky": "husky",
    "Chihuahua": "chihuahua",
    "Boxer": "boxer",
    "Shih Tzu": "shihtzu",
    "Dachshund": "dachshund",
    "Great Dane": "dane/great",
    "Pomeranian": "pomeranian",
    "Border Collie": "collie/border",
    "Australian Shepherd": "australian/shepherd",
    "Doberman Pinscher": "doberman",
    "Rottweiler": "rottweiler",
    "Cavalier King Charles Spaniel": "spaniel/cavalier",
    "Pug": "pug",
    "Corgi": "corgi/cardigan",
    "Jack Russell Terrier": "terrier/russell",
    "Boston Terrier": "terrier/boston",
    "Bernese Mountain Dog": "mountain/bernese",
    "French Bulldog": "bulldog/french"
};

// Questions to ask the user
const questions = [
    { id: "size", question: "How important is having a larger dog?", attribute: "size" },
    { id: "energy", question: "How important is having an energetic, playful dog?", attribute: "energy" },
    { id: "shedding", question: "How concerned are you about shedding? (10 = very concerned)", attribute: "shedding", invert: true },
    { id: "vocal", question: "How important is having a vocal, barking dog?", attribute: "vocal" },
    { id: "friendly", question: "How important is having a dog that's social and friendly with strangers?", attribute: "friendly" },
    { id: "independence", question: "How important is having a dog that's independent and can be left alone?", attribute: "independence" },
    { id: "grooming", question: "How concerned are you about grooming requirements? (10 = very concerned)", attribute: "grooming", invert: true },
    { id: "affection", question: "How important is having an affectionate, cuddly dog?", attribute: "affection" },
    { id: "intelligence", question: "How important is having an intelligent, trainable dog?", attribute: "intelligence" },
    { id: "child_friendly", question: "How important is having a dog that gets along well with children?", attribute: "child_friendly" },
    { id: "pet_friendly", question: "How important is having a dog that gets along with other pets?", attribute: "pet_friendly" },
    { id: "health", question: "How important is having a breed with fewer health issues?", attribute: "health" },
    { id: "lifespan", question: "How important is having a dog with a longer lifespan?", attribute: "lifespan" },
    { id: "adaptability", question: "How important is having a dog that adapts well to changes?", attribute: "adaptability" },
    { id: "indoor_preference", question: "How important is having a dog that's comfortable staying indoors?", attribute: "indoor_preference" },
    { id: "daytime_active", question: "How important is having a dog that's active during the day rather than night?", attribute: "daytime_active" },
    { id: "cost", question: "How concerned are you about the cost of ownership? (10 = very concerned)", attribute: "cost", invert: true },
    { id: "hunting", question: "How important is having a dog with strong hunting instincts?", attribute: "hunting" }
];